# # MoveIt uses this configuration for controller management
# trajectory_execution:
#   allowed_execution_duration_scaling: 1.2
#   allowed_goal_duration_margin: 0.5
#   allowed_start_tolerance: 0.01

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   # controller_names:
#   #   - robot_arm_controller
#   #   - hand_controller

#   # robot_arm_controller:
#   #   action_ns: follow_joint_trajectory
#   #   type: FollowJointTrajectory
#   #   joints:
#   #     - robot_joint1
#   #     - robot_joint2
#   #     - robot_joint3
#   #     - robot_joint4
#   #     - robot_joint5
#   #     - robot_joint6
#   # hand_controller:
#   #   action_ns: follow_joint_trajectory
#   #   type: FollowJointTrajectory
#   #   joints:
#   #     - robot_finger_joint1
#   #     - Tip_Gripper_Servo_Joint
#   #     - robot_finger_joint2
#   #     - Tip_Gripper_Idol_Joint


  controller_names:
    - robot_controller
    - hand_controller

  robot_controller:
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - robot_joint1
        - robot_joint2
        - robot_joint3
        - robot_joint4
        - robot_joint5
        - robot_joint6
        - position

  hand_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - robot_finger_joint1
      - Tip_Gripper_Servo_Joint
      - robot_finger_joint2
      - Tip_Gripper_Idol_Joint
