# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.445
    wheel_radius: 0.0625
    use_stamped_vel: false

robot_arm_controller:
  ros__parameters:
    joints:
      - robot_joint1
      - robot_joint2
      - robot_joint3
      - robot_joint4
      - robot_joint5
      - robot_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

hand_controller:
  ros__parameters:
    joints:
      - robot_finger_joint1
      - Tip_Gripper_Servo_Joint
      - robot_finger_joint2
      - Tip_Gripper_Idol_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity